services:
  - type: web
    name: picoshare
    env: docker
    repo: https://github.com/mtlynch/picoshare
    envVars:
      - key: PORT
        value: 3001
      - key: PS_SHARED_SECRET
        value: 123456
    healthCheckPath: /
  #  disk:
   #   name: data
    #  mountPath: /data
